### ISSUE TITLE
can't compile for SDL1

### ISSUE THREAD

**Issue by bam80** [Ancurio/SDL_sound#11]
```
configure: error: *** SDL version 2.0.0 not found!

**Comment by Ancurio** [comment]
I created this fork of SDL_sound mainly as an accumulation of all the fixes required to make it work for mkxp, which only uses SDL2. Is there a specific reason you want to use SDL1? It's been deprecated a long time ago.

Otherwise you can try out the official version on http://icculus.org/SDL_sound/

**Comment by bam80** [comment]
Unfortunately, I still have to use SDL1 because of DOSBox.
I thought this repo is just a mirror of original one. Sorry.
